services:
  backend:
    image: m1ll3r1337/treffly-server:latest
    expose:
      - "8080"
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge