-- +goose Up
-- +goose StatementBegin
CREATE TABLE "tags" (
                        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "user_tags" (
                             "user_id" integer NOT NULL,
                             "tag_id" integer NOT NULL,
                             PRIMARY KEY ("user_id", "tag_id")
);

CREATE INDEX "idx_tags_name" ON "tags" ("name");

ALTER TABLE "user_tags" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "user_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE;

INSERT INTO tags (name)
VALUES
    ('Искусство'),
    ('Театр'),
    ('Кино'),
    ('Музыка'),
    ('Танцы'),
    ('Литература'),
    ('Наука'),
    ('Технологии'),
    ('Космос'),
    ('Инновации'),
    ('Фестивали'),
    ('Игры'),
    ('Юмор'),
    ('Мода'),
    ('Фото'),
    ('Образование'),
    ('Языки'),
    ('Психология'),
    ('Карьера'),
    ('Спорт'),
    ('Йога'),
    ('Туризм'),
    ('Велоспорт'),
    ('Экстрим'),
    ('Гастрономия'),
    ('Вегетарианство'),
    ('Дегустация'),
    ('Благотворительность'),
    ('Экология'),
    ('Волонтерство')
    ON CONFLICT (name) DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE user_tags;
DROP TABLE tags;
-- +goose StatementEnd
