-- +goose Up
-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE "events" (
                          "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar(100) NOT NULL,
                          "description" text NOT NULL,
                          "capacity" integer NOT NULL,
                          "latitude" numeric(10,8) NOT NULL,
                          "longitude" numeric(11,8) NOT NULL,
                          "address" text NOT NULL,
                          "date" timestamptz NOT NULL,
                          "owner_id" integer NOT NULL,
                          "is_private" boolean NOT NULL DEFAULT false,
                          "is_premium" boolean NOT NULL DEFAULT false,
                          "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "event_user" (
                              "user_id" integer NOT NULL,
                              "event_id" integer NOT NULL,
                              PRIMARY KEY ("user_id", "event_id")
);

CREATE TABLE "event_tags" (
                              "event_id" integer NOT NULL,
                              "tag_id" integer NOT NULL,
                              PRIMARY KEY ("event_id", "tag_id")
);

CREATE INDEX "idx_events_owner_id" ON "events" ("owner_id");

CREATE INDEX "idx_event_user_event_id" ON "event_user" ("event_id");

CREATE INDEX idx_events_date ON "events" ("date");

ALTER TABLE "events" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "event_user" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "event_user" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;

ALTER TABLE "event_tags" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;

ALTER TABLE "event_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE;


-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE event_tags;
DROP TABLE event_user;
DROP TABLE EVENTS;
-- +goose StatementEnd
