-- +goose Up
-- +goose StatementBegin
CREATE TYPE "orders_status" AS ENUM (
  'pending',
  'complete'
);

CREATE TABLE "premium_orders" (
                                  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "user_id" integer NOT NULL,
                                  "event_id" integer NOT NULL,
                                  "shop" varchar(50) NOT NULL,
                                  "price" decimal NOT NULL,
                                  "status" orders_status NOT NULL DEFAULT 'pending',
                                  "created_at" timestamptz NOT NULL DEFAULT (now())
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE premium_orders;
DROP TYPE orders_status;
-- +goose StatementEnd
