// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: image.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (
    id,
    path
) VALUES (
             $1,
             $2
         )
RETURNING id, path
`

type CreateImageParams struct {
	ID   uuid.UUID `json:"id"`
	Path string    `json:"path"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage, arg.ID, arg.Path)
	var i Image
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}
