// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID               int32     `json:"id"`
	UserID           int32     `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	ExpiresAt        time.Time `json:"expires_at"`
	IsBlocked        bool      `json:"is_blocked"`
	CreatedAt        time.Time `json:"created_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    time.Time    `json:"created_at"`
	IsAdmin      sql.NullBool `json:"is_admin"`
}
