// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddEventTag(ctx context.Context, arg AddEventTagParams) (EventTag, error)
	AddUserTag(ctx context.Context, arg AddUserTagParams) (UserTag, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllEventTags(ctx context.Context, eventID int32) error
	DeleteEvent(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteUserTag(ctx context.Context, arg DeleteUserTagParams) error
	GetAllUserTags(ctx context.Context, id int32) ([]Tag, error)
	GetEvent(ctx context.Context, id int32) (EventWithTagsView, error)
	GetSession(ctx context.Context, argUuid uuid.UUID) (Session, error)
	GetTags(ctx context.Context) ([]Tag, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserWithTags(ctx context.Context, id int32) (UserWithTagsView, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]EventWithTagsView, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
