// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username,
                   email,
                   password_hash)
VALUES ($1, $2, $3) RETURNING id, username, email, password_hash, created_at, is_admin, image_id
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.ImageID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password_hash, created_at, is_admin, image_id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.ImageID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, is_admin, image_id FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.ImageID,
	)
	return i, err
}

const getUserWithTags = `-- name: GetUserWithTags :one
SELECT id, username, email, created_at, tags, image_path FROM user_with_tags_view WHERE id = $1
`

func (q *Queries) GetUserWithTags(ctx context.Context, id int32) (UserWithTagsView, error) {
	row := q.db.QueryRow(ctx, getUserWithTags, id)
	var i UserWithTagsView
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.Tags,
		&i.ImagePath,
	)
	return i, err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS (
    SELECT 1
    FROM event_user
    WHERE event_id = $1
      AND user_id = $2
) AS is_participant
`

type IsParticipantParams struct {
	EventID int32 `json:"event_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.EventID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, created_at, is_admin, image_id FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.IsAdmin,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeToEvent = `-- name: SubscribeToEvent :one
WITH event_check AS (
    SELECT
        e.capacity,
        e.is_private,
        COUNT(eu.user_id) AS participants,
        EXISTS (
            SELECT 1 FROM event_tokens
            WHERE event_id = e.id
              AND token = $3
              AND (expires_at > NOW())
        ) AS valid_token
    FROM events e
             LEFT JOIN event_user eu ON e.id = eu.event_id
    WHERE e.id = $2
    GROUP BY e.id
)
INSERT INTO event_user (user_id, event_id)
SELECT $1, $2
FROM event_check
WHERE
    participants < capacity
  AND (
    NOT is_private
        OR
    (is_private AND valid_token)
    )
    RETURNING (
    SELECT participants < capacity
    AND (NOT is_private OR valid_token)
    FROM event_check
) AS allowed
`

type SubscribeToEventParams struct {
	UserID  int32  `json:"user_id"`
	EventID int32  `json:"event_id"`
	Token   string `json:"token"`
}

func (q *Queries) SubscribeToEvent(ctx context.Context, arg SubscribeToEventParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, subscribeToEvent, arg.UserID, arg.EventID, arg.Token)
	var allowed pgtype.Bool
	err := row.Scan(&allowed)
	return allowed, err
}

const unsubscribeFromEvent = `-- name: UnsubscribeFromEvent :exec
DELETE FROM event_user
WHERE user_id = $1 AND event_id = $2
`

type UnsubscribeFromEventParams struct {
	UserID  int32 `json:"user_id"`
	EventID int32 `json:"event_id"`
}

func (q *Queries) UnsubscribeFromEvent(ctx context.Context, arg UnsubscribeFromEventParams) error {
	_, err := q.db.Exec(ctx, unsubscribeFromEvent, arg.UserID, arg.EventID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2,
    image_id = $3
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, is_admin, image_id
`

type UpdateUserParams struct {
	ID       int32       `json:"id"`
	Username string      `json:"username"`
	ImageID  pgtype.UUID `json:"image_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Username, arg.ImageID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.ImageID,
	)
	return i, err
}
